import type { Task } from './apiTypes';

// API Task 형식에 맞춘 Mock Data (계층 구조)
export const mockHierarchicalTasks: Task[] = [
  {
    task_id: '1',
    parent_id: null,
    name: '1단계: 프로젝트 기획 및 설계',
    assignee: 'PM',
    start_date: '2024-01-01',
    end_date: '2024-01-21',
    duration_days: 21,
    progress: 85,
    status: '진행중',
    subtasks: [
      {
        task_id: '1.1',
        parent_id: '1',
        name: '요구사항 분석 및 정의',
        assignee: '기획자',
        start_date: '2024-01-01',
        end_date: '2024-01-07',
        duration_days: 7,
        progress: 100,
        status: '완료',
        subtasks: [],
      },
      {
        task_id: '1.2',
        parent_id: '1',
        name: '시스템 아키텍처 설계',
        assignee: '아키텍트',
        start_date: '2024-01-08',
        end_date: '2024-01-14',
        duration_days: 7,
        progress: 100,
        status: '완료',
        subtasks: [],
      },
      {
        task_id: '1.3',
        parent_id: '1',
        name: 'UI/UX 디자인 및 프로토타입',
        assignee: '디자이너',
        start_date: '2024-01-15',
        end_date: '2024-01-21',
        duration_days: 7,
        progress: 60,
        status: '진행중',
        subtasks: [],
      },
    ],
  },
  {
    task_id: '2',
    parent_id: null,
    name: '2단계: 백엔드 개발',
    assignee: '백엔드 팀장',
    start_date: '2024-01-22',
    end_date: '2024-02-18',
    duration_days: 28,
    progress: 45,
    status: '진행중',
    subtasks: [
      {
        task_id: '2.1',
        parent_id: '2',
        name: '데이터베이스 설계 및 구축',
        assignee: 'DBA',
        start_date: '2024-01-22',
        end_date: '2024-01-28',
        duration_days: 7,
        progress: 100,
        status: '완료',
        subtasks: [],
      },
      {
        task_id: '2.2',
        parent_id: '2',
        name: 'AI 모델 개발 및 훈련',
        assignee: 'AI 개발자',
        start_date: '2024-01-29',
        end_date: '2024-02-11',
        duration_days: 14,
        progress: 30,
        status: '진행중',
        subtasks: [],
      },
      {
        task_id: '2.3',
        parent_id: '2',
        name: 'API 서버 개발',
        assignee: '백엔드 개발자',
        start_date: '2024-02-05',
        end_date: '2024-02-18',
        duration_days: 14,
        progress: 20,
        status: '할일',
        subtasks: [],
      },
    ],
  },
  {
    task_id: '3',
    parent_id: null,
    name: '3단계: 프론트엔드 개발',
    assignee: '프론트엔드 팀장',
    start_date: '2024-02-12',
    end_date: '2024-03-10',
    duration_days: 28,
    progress: 15,
    status: '할일',
    subtasks: [
      {
        task_id: '3.1',
        parent_id: '3',
        name: '사용자 인터페이스 구현',
        assignee: 'UI 개발자',
        start_date: '2024-02-12',
        end_date: '2024-02-25',
        duration_days: 14,
        progress: 40,
        status: '진행중',
        subtasks: [],
      },
      {
        task_id: '3.2',
        parent_id: '3',
        name: '간트차트 컴포넌트 개발',
        assignee: '프론트엔드 개발자',
        start_date: '2024-02-19',
        end_date: '2024-03-03',
        duration_days: 14,
        progress: 10,
        status: '할일',
        subtasks: [],
      },
      {
        task_id: '3.3',
        parent_id: '3',
        name: '칸반보드 기능 구현',
        assignee: '프론트엔드 개발자',
        start_date: '2024-02-26',
        end_date: '2024-03-10',
        duration_days: 14,
        progress: 0,
        status: '할일',
        subtasks: [],
      },
    ],
  },
  {
    task_id: '4',
    parent_id: null,
    name: '4단계: 통합 및 테스트',
    assignee: 'QA 팀장',
    start_date: '2024-03-04',
    end_date: '2024-03-24',
    duration_days: 21,
    progress: 0,
    status: '할일',
    subtasks: [
      {
        task_id: '4.1',
        parent_id: '4',
        name: '시스템 통합 테스트',
        assignee: 'QA 엔지니어',
        start_date: '2024-03-04',
        end_date: '2024-03-17',
        duration_days: 14,
        progress: 0,
        status: '할일',
        subtasks: [],
      },
      {
        task_id: '4.2',
        parent_id: '4',
        name: '사용자 수용 테스트',
        assignee: 'QA 엔지니어',
        start_date: '2024-03-11',
        end_date: '2024-03-24',
        duration_days: 14,
        progress: 0,
        status: '할일',
        subtasks: [],
      },
    ],
  },
];
